import os
from setuptools import setup, find_packages


with open("README.md", "r") as f:
    long_description = f.read()

with open("requirements.txt", "r") as f:
    install_requires = [line.strip() for line in f]

version = "0.1.0"

with open(os.path.join("sroom", "version.py"), "w") as f:
    f.writelines([
        '"""This file is auto-generated by setup.py, please do not alter."""\n',
        f'__version__ = "{version}"\n',
        "",
    ])

setup(
    name='sroom',
    version=version,
    description='Simulate a smart room by voice commands',
    long_description=long_description,
    long_description_content_type="text/markdown",
    author="thanhtvt",
    url='https://github.com/thanhtvt/SmartRoomSimulator',
    packages=find_packages(),
    install_requires=install_requires,
    python_requires='>=3.7',
)
